"""baseline_schema

Revision ID: ddae20f65454
Revises: 
Create Date: 2026-05-23 01:28:42.025511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddae20f65454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finders',
    sa.Column('finder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('finder_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('student', 'staff', 'admin', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_token_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('found_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('finder_id', sa.Integer(), nullable=True),
    sa.Column('logged_by', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('location_found', sa.String(length=120), nullable=True),
    sa.Column('date_found', sa.Date(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('logged', 'matched', 'released', name='found_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finder_id'], ['finders.finder_id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('lost_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('date_lost', sa.Date(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('reported', 'matched', 'claimed', 'closed', name='lost_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('lost_report_id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_items.item_id'], ),
    sa.ForeignKeyConstraint(['lost_report_id'], ['lost_reports.report_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('found_item_id'),
    sa.UniqueConstraint('lost_report_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('claimant_id', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'released', name='claim_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    op.drop_table('matches')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    op.drop_table('lost_reports')
    op.drop_table('found_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('finders')
    # ### end Alembic commands ###
